"""Backtest report generation.

Generates markdown reports from ``BacktestResult`` objects, and optionally
integrates with the existing ``report_writer`` for on-disk output.
"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)


def generate_backtest_report(result, save_path: str | Path | None = None) -> str:
    """Generate a markdown report from a BacktestResult.

    Args:
        result: A ``BacktestResult`` instance.
        save_path: Optional path to save the report. If None, only returns
            the markdown string.

    Returns:
        Markdown string of the backtest report.
    """
    lines = [
        f"# Backtest Report: {result.ticker}",
        "",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"**Decision:** {result.decision}",
        f"**Holding Period:** {result.holding_days} days",
        "",
        "## Performance Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
    ]

    def _fmt(val, fmt_str=".2%", is_pct=True):
        if val is None:
            return "N/A"
        return f"{val:{fmt_str}}" if is_pct else f"{val}"

    lines.append(f"| Initial Cash | ¥{result.initial_cash:,.0f} |")
    if result.final_value is not None:
        lines.append(f"| Final Value | ¥{result.final_value:,.0f} |")
    if result.total_return is not None:
        lines.append(f"| Total Return | {result.total_return:+.2%} |")
    if result.annual_return is not None:
        lines.append(f"| Annual Return | {result.annual_return:+.2%} |")
    if result.sharpe_ratio is not None:
        lines.append(f"| Sharpe Ratio | {result.sharpe_ratio:.2f} |")
    if result.max_drawdown is not None:
        lines.append(f"| Max Drawdown | {result.max_drawdown:.2%} |")
    if result.total_trades > 0:
        lines.append(f"| Total Trades | {result.total_trades} |")
        lines.append(f"| Win Rate | {result.win_rate:.1%} |" if result.win_rate else "")
        lines.append(f"| Profit Trades | {result.profit_trades} |")
        lines.append(f"| Loss Trades | {result.loss_trades} |")

    lines.extend([
        "",
        "## Analysis",
        "",
    ])

    # Generate analysis text based on results
    if result.decision == "HOLD":
        lines.append("Decision was HOLD — no position was taken.")
    elif result.total_return is not None:
        if result.total_return > 0:
            lines.append(f"The {result.decision} decision was profitable with a {result.total_return:+.2%} return.")
        else:
            lines.append(f"The {result.decision} decision resulted in a {result.total_return:+.2%} loss.")
        if result.max_drawdown is not None and result.max_drawdown < -0.10:
            lines.append(f"⚠️ Significant drawdown of {result.max_drawdown:.2%} was observed.")
        if result.sharpe_ratio is not None:
            if result.sharpe_ratio > 1.0:
                lines.append("Good risk-adjusted returns (Sharpe > 1.0).")
            elif result.sharpe_ratio < 0:
                lines.append("Negative risk-adjusted returns.")
    else:
        lines.append("Insufficient data to evaluate the decision.")

    lines.extend(["", "---", f"*Generated by TradingAgents Backtesting Engine*"])

    report = "\n".join(lines)

    if save_path is not None:
        save_path = Path(save_path)
        save_path.parent.mkdir(parents=True, exist_ok=True)
        save_path.write_text(report, encoding="utf-8")
        logger.info("Backtest report saved to %s", save_path)

    return report


def save_backtest_report(result, ticker: str, config: dict) -> Path:
    """Save a backtest report to the standard results directory.

    Returns the path where the report was saved.
    """
    from tradingagents.dataflows.utils import safe_ticker_component

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    results_dir = Path(config.get("results_dir", "results"))
    save_path = (
        results_dir / "backtest" / f"{safe_ticker_component(ticker)}_{stamp}.md"
    )
    generate_backtest_report(result, save_path=save_path)
    return save_path
